const cStandard = 'c11';
const cppStandard = 'c++11';

module.exports = {
  configurations: [
    {
      configureFilter: 'linux',
      configureSource: 'https://code.visualstudio.com/docs/cpp/config-linux',
      name: 'Linux / g++',
      includePath: [],
      defines: [],
      compilerPath: '/usr/bin/gcc',
      cStandard,
      cppStandard,
      intelliSenseMode: 'gcc-x64',
    },
    {
      configureFilter: 'linux',
      configureSource: 'https://code.visualstudio.com/docs/cpp/config-linux',
      name: 'Linux / Clang',
      includePath: [],
      defines: [],
      compilerPath: '/usr/bin/gcc',
      cStandard,
      cppStandard,
      intelliSenseMode: 'clang-x64',
    },
    {
      configureFilter: 'darwin',
      configureSource: 'https://code.visualstudio.com/docs/cpp/config-clang-mac',
      name: 'MacOS / Clang',
      includePath: [],
      defines: [],
      macFrameworkPath: ['/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks'],
      compilerPath: '/usr/bin/clang',
      cStandard,
      cppStandard,
      intelliSenseMode: 'clang-x64',
    },
    {
      configureFilter: 'win32',
      configureSource: 'https://code.visualstudio.com/docs/cpp/config-msvc',
      name: 'Windows / MSVC',
      includePath: [],
      defines: ['_DEBUG', 'UNICODE', '_UNICODE'],
      windowsSdkVersion: '10.0.18362.0',
      compilerPath:
        'C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe',
      cStandard,
      cppStandard,
      intelliSenseMode: 'msvc-x64',
    },
    {
      configureFilter: 'win32',
      configureSource: 'https://code.visualstudio.com/docs/cpp/config-mingw',
      name: 'Windows / GCC',
      includePath: [],
      defines: ['_DEBUG', 'UNICODE', '_UNICODE'],
      windowsSdkVersion: '10.0.18362.0',
      compilerPath: 'C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/g++.exe',
      cStandard,
      intelliSenseMode: 'gcc-x64',
    },
    {
      configureFilter: 'win32',
      configureSource: 'https://code.visualstudio.com/docs/cpp/config-wsl',
      name: 'Windows / WSL / GCC',
      includePath: [],
      defines: [],
      compilerPath: '/usr/bin/gcc',
      cStandard,
      cppStandard,
      intelliSenseMode: 'clang-x64',
    },
  ],
  version: 4,
};
