# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # build-system: [gyp, cmake, xmake]
        build-system: [gyp, cmake]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Make CLang Available
      run: sudo apt-get install -y clang-tidy clang-format
    - name: Make Build System Available (CMake)
      run: sudo apt-get install -y cmake
      if: ${{ matrix.build-system == 'cmake' }}
    # - name: Make Build System Available (CMake)
    #   run: bash <(curl -fsSL https://xmake.io/shget.text)
    #   if: ${{ matrix.build-system == 'xmake' }}
    - name: Init
      run: npm i && node .scripts/configure.js -x ${{ matrix.build-system }} -e none
    - name: Code Analysis
      run: npm run ca
    - name: Code UnitTests
      run: npm run test
    - name: Code Build
      run: npm run build
    - name: Code Docs
      if: ${{ matrix.node-version == '14.x' }}
      run: npm run docs
